[project]
name = "llm4cap"
version = "0.0.1"
description = "Ein Tool, welches die Arbeit mit Ontologien vereinfachen soll und dazu Erklärungen, wie auch Visualisierungen bereitstellt. Außerdem soll es die Erstellung selbiger vereinfachen, durch den Einsatz von LLMs und der Prüfung von daraus entstandenen Ontologien, mithilfe von Python Bibliotheken."
authors = [
    {name = "Luis Miguel Vieira da Silva",email = "miguel.vieira@hsu-hh.de"},
    {name = "Aljosha Köcher",email = "aljosha.koecher@hsu-hh.de"},
    {name = "Jan Niklas Storm",email = "m778460@hsu-hh.de"}
]
license = {text = "MIT"}
readme = "README.md"
packages = [{include = "llm4cap", from = "src"}]

[tool.poetry.scripts]
llm4cap = "llm4cap.__main__:main"

[tool.poetry.dependencies]
python = ">=3.13,<4.0.0"
openai = ">=1.95.1,<2.0.0"
rdflib = ">=7.1.4,<8.0.0"
pyvis-network = ">=0.0.6,<0.0.7"
owlready2 = ">=0.48,<0.49"
pyshacl = ">=0.30.1,<0.31.0"
owlrl = ">=7.1.3,<8.0.0"
# Achtung: pyqt5 nicht direkt via Poetry installierbar
# Manuell per pip in virtueller Umgebung über poetry shell installieren:
# pip install pyqt5 pyqtwebengine
pyvis = "^0.3.2"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
